name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  Tests:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        swift test --verbose
